//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLSLLanguageIntegration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLSLLanguageIntegration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16x {
            get {
                object obj = ResourceManager.GetObject("Comment_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Comment_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16x_32 {
            get {
                object obj = ResourceManager.GetObject("Comment_16x_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment_16xMD {
            get {
                object obj = ResourceManager.GetObject("comment_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16xMD_32 {
            get {
                object obj = ResourceManager.GetObject("Comment_16xMD_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment_16xSM {
            get {
                object obj = ResourceManager.GetObject("comment_16xSM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16xSM_24 {
            get {
                object obj = ResourceManager.GetObject("Comment_16xSM_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16xSM_32 {
            get {
                object obj = ResourceManager.GetObject("Comment_16xSM_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_16xSM_Green24 {
            get {
                object obj = ResourceManager.GetObject("Comment_16xSM_Green24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment_noHalo_16x {
            get {
                object obj = ResourceManager.GetObject("Comment_noHalo_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CommentFilled_16x {
            get {
                object obj = ResourceManager.GetObject("CommentFilled_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_16x {
            get {
                object obj = ResourceManager.GetObject("Constant_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Constant_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_left_16x {
            get {
                object obj = ResourceManager.GetObject("Constant_left_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_left_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Constant_left_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Constant_left_16x_32 {
            get {
                object obj = ResourceManager.GetObject("Constant_left_16x_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to const ivec3 gl_MaxComputeWorkGroupCount = { 65535, 65535, 65535 };
        ///
        ///const ivec3 gl_MaxComputeWorkGroupSize = { 1024, 1024, 64 };
        ///
        ///const int gl_MaxComputeUniformComponents = 512;
        ///
        ///const int gl_MaxComputeTextureImageUnits = 16;
        ///
        ///const int gl_MaxComputeImageUniforms = 8;
        ///
        ///const int gl_MaxComputeAtomicCounters = 8;
        ///
        ///const int gl_MaxComputeAtomicCounterBuffers = 8;
        ///
        ///const int gl_MaxVertexAttribs = 16;
        ///
        ///const int gl_MaxVertexUniformComponents = 1024;
        ///
        ///const int gl_MaxVaryingComponents = 60;
        ///
        ///c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Constants {
            get {
                return ResourceManager.GetString("Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap data_number_on_16x {
            get {
                object obj = ResourceManager.GetObject("data_number_on_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap data_number_on_16x_24 {
            get {
                object obj = ResourceManager.GetObject("data_number_on_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///
        ///#define
        ///
        ///#undef
        ///
        ///#if
        ///
        ///#ifdef
        ///
        ///#ifndef
        ///
        ///#else
        ///
        ///#elif
        ///
        ///#endif
        ///
        ///#error
        ///
        ///#pragma
        ///
        ///#extension
        ///
        ///#version
        ///
        ///#line
        ///
        ///defined
        ///
        ///##
        ///.
        /// </summary>
        internal static string Directives {
            get {
                return ResourceManager.GetString("Directives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radians
        ///Converts degrees to radians, i.e., pi / 180 ⋅degrees
        ///
        ///degrees
        ///Converts radians to degrees, i.e., 180 / pi radians
        ///
        ///sin
        ///The standard trigonometric sine function.
        ///
        ///cos
        ///The standard trigonometric cosine function.
        ///
        ///tan
        ///The standard trigonometric tangent.
        ///
        ///asin
        ///Arc sine. Returns an angle whose sine is x.
        ///The range of values returned by this function is [−pi / 2, pi / 2]
        ///Results are undefined if ∣x∣ &gt; 1.
        ///
        ///acos
        ///
        ///atan
        ///
        ///sinh
        ///
        ///cosh
        ///
        ///tanh
        ///
        ///asinh
        ///
        ///acosh
        ///
        ///atanh
        ///
        ///pow
        ///
        ///exp
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gl_NumWorkGroups
        ///
        ///gl_WorkGroupSize
        ///
        ///gl_WorkGroupID
        ///
        ///gl_LocalInvocationID
        ///
        ///gl_GlobalInvocationID
        ///
        ///gl_LocalInvocationIndex
        ///
        ///gl_VertexID
        ///
        ///gl_VertexIndex
        ///
        ///gl_InstanceID
        ///
        ///gl_InstanceIndex
        ///
        ///gl_PerVertex
        ///
        ///gl_Position
        ///
        ///gl_PointSize
        ///
        ///gl_in
        ///
        ///gl_PrimitiveIDIn
        ///
        ///gl_Layer
        ///
        ///gl_ViewportIndex
        ///
        ///gl_PatchVerticesIn
        ///
        ///gl_InvocationID
        ///
        ///gl_TessLevelOuter
        ///
        ///gl_TessLevelInner
        ///
        ///gl_TessCoord
        ///
        ///gl_FragColor
        ///
        ///gl_FragCoord
        ///
        ///gl_FrontFacing
        ///
        ///gl_ClipDistance
        ///
        ///gl_CullDistance
        ///
        ///gl_PointCoord [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Identifiers {
            get {
                return ResourceManager.GetString("Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute
        ///compatibility profile only and vertex language only; same as in when in a vertex shader
        ///
        ///const
        ///a variable whose value cannot be changed
        ///
        ///uniform
        ///value does not change across the primitive being processed, uniforms form the linkage between a shader, OpenGL, and the application
        ///
        ///varying
        ///compatibility profile only and vertex and fragment languages only; same as out when in a vertex shader and same as in when in a fragment shader
        ///
        ///buffer
        ///value is stored in a buffer object, and can be read [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16x {
            get {
                object obj = ResourceManager.GetObject("Numeric_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Numeric_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16x_32 {
            get {
                object obj = ResourceManager.GetObject("Numeric_16x_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16xMD {
            get {
                object obj = ResourceManager.GetObject("Numeric_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16xMD_24 {
            get {
                object obj = ResourceManager.GetObject("Numeric_16xMD_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Numeric_16xMD_32 {
            get {
                object obj = ResourceManager.GetObject("Numeric_16xMD_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_16x {
            get {
                object obj = ResourceManager.GetObject("Operator_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Operator_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_16x_32 {
            get {
                object obj = ResourceManager.GetObject("Operator_16x_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_Grey_16x {
            get {
                object obj = ResourceManager.GetObject("Operator_Grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_left_16x {
            get {
                object obj = ResourceManager.GetObject("Operator_left_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_left_16x_24 {
            get {
                object obj = ResourceManager.GetObject("Operator_left_16x_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Operator_left_16x_32 {
            get {
                object obj = ResourceManager.GetObject("Operator_left_16x_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OperatorCircle_16x {
            get {
                object obj = ResourceManager.GetObject("OperatorCircle_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void
        ///for functions that do not return a value
        ///
        ///bool
        ///a conditional type, taking on values of true or false
        ///
        ///int
        ///a signed integer
        ///
        ///uint
        ///an unsigned integer
        ///
        ///float
        ///a single-precision floating-point scalar
        ///
        ///double
        ///a double-precision floating-point scalar
        ///
        ///vec2
        ///a two-component single-precision floating-point vector
        ///
        ///vec3
        ///a three-component single-precision floating-point vector
        ///
        ///vec4
        ///a four-component single-precision floating-point vector
        ///
        ///dvec2
        ///a two-component double-precision floatin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
