namespace GLSLLanguageIntegration.Tokens
{
    public enum GLSLTokenTypes
    {
        None,
        PreprocessorDirective,
        Comment,
        Keyword,
        Type,
        InputVariable,
        OutputVariable,
        UniformVariable,
        BufferVariable,
        SharedVariable,
        BuiltInVariable,
        LocalVariable,
        ParameterVariable,
        Struct,
        IntegerConstant,
        FloatingConstant,
        BuiltInConstant,
        Function,
        BuiltInFunction,
        Operator,
        Semicolon,
        Parenthesis,
        CurlyBracket,
        SquareBracket
    }
}
